### ISSUE TITLE
This option is not working.

### ISSUE THREAD

**Issue by mxmkmarquette** [o10n-x/wordpress-pwa-optimization#2]
when i click on the box it just don't stick. 

CSS online/offline class | EnabledAdd the class offline to <body> based on HTML5 online/offline events. This feature enables to add a user friendly notice via CSS when the connection is offline. This option also enables the API o10n.on('offline', fn);.
-- | --

**Comment by optimalisatie** [comment]
Hi Maxime,

Thanks a lot for reporting the issue!

The issue has been resolved in `v0.0.13`.
